function instructions(s)

WaitSecs(0.5);
DrawFormattedText(s.display.w,...
                    ['In this game, you will try\n\n',...
                    'to learn sequences of key presses'],...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;

WaitSecs(0.5);
DrawFormattedText(s.display.w, ...
                   ['Each sequence is associated with a different picture\n\n\n\n', ...
                    'In some runs, you will see two different images\n\n', ...
                    'and you can choose which to practice.\n\n\n\n',...
                    'Use the "' s.responses.keyLabels{s.responses.choiceKeys(1)} '" and "' s.responses.keyLabels{s.responses.choiceKeys(2)} '" buttons to pick\n\nTry it!'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;

WaitSecs(0.5);
getCueChoice(s, 1, 1, 1, [], GetSecs, 0, 'choice', 'instructions')


WaitSecs(0.5);
DrawFormattedText(s.display.w, ...
                  ['On other runs, you don''t get to choose, but you will\n\n',...
                    'still see the images so know which sequence you''ll be practicing.\n\n\n\n', ...
                    'Pick the selected image to start the trial.'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;

WaitSecs(0.5);
getCueChoice(s, 1, 1, 1, [], GetSecs, 0, 'control', 'instructions')



WaitSecs(0.5);
DrawFormattedText(s.display.w, ...
                   ['After picking an image, you''ll watch the\n\n', ...
                    'sequence that goes with it.'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;

viewSequence(s, 0, 0, 0, -1);
WaitSecs(0.5);
clearScreen(s);

DrawFormattedText(s.display.w, ...
                   ['After you''ve seen it, wait until the circles\n\n', ...
                    'turn yellow, and then try to repeat the sequence\n\n\n\n', ...
                    'Use the buttons  ' sprintf('"%s" ', s.responses.keyLabels{:}) '  to respond'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;
showTargets(s,s.display.viewColor);
WaitSecs(0.5);
testSequence(s, 0, 0, 0, -1, NaN, 'test');

WaitSecs(0.5);
DrawFormattedText(s.display.w, ...
                   ['At the end of each block, you''ll be tested\n\n', ...
                    'on the sequences you saw.\n\n\n\n',...
                    'First you''ll see the image with a green box around it:'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;

getCueChoice(s, 1, 1, 1, [], GetSecs, 0, 'control', 'instructions_test')

WaitSecs(0.5);
DrawFormattedText(s.display.w, ...
                   ['Then you''ll be asked to repeat the sequence that\n\n',...
                    'goes with it, but this time, without watching it first.'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;

WaitSecs(0.5);
testSequence(s, 0, 0, 0, -1, NaN, 'test');

WaitSecs(0.5);
DrawFormattedText(s.display.w, ...
                   ['Great! Press a key when you''re ready to start,\n\n',...
                    'and then we''ll wait for the scanner to start.'], ...
                    'center','center', s.display.textColor);
Screen('Flip', s.display.w);
KbWait;